#include "test/test.h"

// Special __start_<section> and __stop_<section> symbols generated by GCC.
extern const struct test_info __start_test_rodata;
extern const struct test_info __stop_test_rodata;

const struct test_info *const tests_begin = &__start_test_rodata;
const struct test_info *const tests_end = &__stop_test_rodata;

// Run all tests.
void run_tests(const char *selection) {
  assert(selection);
  printf("\r\nRunning tests with selection '%s'...\r\n", selection);

  bool test_passed;
  for (const struct test_info *test = tests_begin; test < tests_end; ++test) {
    test_passed = true;
    printf("Running test %s...\r\n", test->name);
    test->fn(&test_passed);
    printf("Test %s\r\n", test_passed ? "PASSED" : "FAILED");
  }

#ifdef RUNTEST
  printf("Done.\r\n");
  for (;;) {
    __asm__("hlt");
  }
#endif // RUNTEST
}
